<?php

/**
 * @file personalize_taxonomy_context.module
 * Provides a visitor context plugin for taxonomy.
 */

/**
 * Implements hook_personalize_visitor_contexts().
 */
function personalize_taxonomy_context_personalize_visitor_context() {
  $info = array();
  $path = drupal_get_path('module', 'personalize_taxonomy_context') . '/plugins';
  $info['taxonomy_context'] = array(
    'path' => $path . '/visitor_context',
    'handler' => array(
      'file' => 'TaxonomyContext.inc',
      'class' => 'TaxonomyContext',
    ),
  );
  return $info;
}
